[versions]
agp = "8.6.0-alpha05"
android-material = "1.12.0"
androidx-navigation = "2.7.7"
androidx-test-espresso = "3.6.0-rc01"
build-android-compileSdk = "34"
build-android-minSdk = "21"
build-android-targetSdk = "34"
build-javaVersion = "VERSION_17"
build-jvmTarget = "17"
detekt = "1.23.6"
kotlin = "2.0.0"
kotlinx-kover = "0.8.1"
ktlint = "1.3.0"

[libraries]
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
